version: '2'
services:
  deepracer:
    build: .
    image: deepracer
    working_dir: /code
    command: [ "/opt/conda/bin/jupyter", "lab", "--allow-root", "--notebook-dir" ,"/code" ,"--ip", "0.0.0.0"]
    volumes:
      - ./aws-deepracer/:/code
      - ~/.aws:/root/.aws
    ports:
      - "8888:8888"
    environment:
      - PYTHONPATH=/code:/code/log-analysis
      - AWS_DEFAULT_PROFILE
      - AWS_DEFAULT_REGION=us-east-1
